{% set name = "pytest-csv" %}
{% set version = "3.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6d01e7db1aa2137eae822d3fdb2d6a5dd0ce736548593b5311ae3cf41e2d12d4

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3
    - pytest >=4.4
    - six >=1.0.0

test:
  imports:
    - pytest_csv
    - pytest_csv.column

about:
  home: https://github.com/nicoulaj/pytest-csv
  license: GPL-3.0-only
  license_family: GPL
  license_file: COPYING
  summary: CSV reporter for pytest.

extra:
  recipe-maintainers:
    - drbixx
    - teake
